### ISSUE TITLE
Double bed filter?

### ISSUE THREAD

**Issue by samiswicked** [gfarrell/KORDS#4]
I know it's not particularly useful but I've always been curious to see which rooms have double beds and I'm sure other people are too, so if it's easy enough maybe you could put it in? Also one problem with using github to deal with requests is that people will have to make accounts, and most people won't be bothered... perhaps suggest github OR E-mail? 

Sami

**Comment by gfarrell** [comment]
Oh. I'm surprised that I didn't put that in, the data is there. I'll put it on my todo list.

**Comment by samiswicked** [comment]
Yeh that's what I thought, hence why I thought it would be an easy one to do, because the double bed info is already there. 

Sami.

**Comment by samiswicked** [comment]
P.S. The only person I can count on to reply to an E-mail within 5 minutes, no matter what the time

**Comment by gfarrell** [comment]
How do you like KORDS otherwise?

**Comment by samiswicked** [comment]
Incredible man, seriously seriously good (I'm guessing you haven't checked your Facebook, because that would have made this question kind of pointless haha...)
